### PR TITLE
Strong mode mirror support for rpc package

### LINKED ISSUE #133: rpc package tests broken with "not a subtype" errors in 2.2+
See dart-lang/sdk#35009.

### PR DESCRIPTION
**Pull request by jcollins-g**
Fixes #133.

@supermuka

I believe this should be a complete set of changes for the rpc package to support strong-mode mirrors (dart-lang/sdk#35611).  It passes all tests on Dart 2.0.0, Dart 2.1.0, and bleeding edge (with strong-mode mirrors) and seems to work just fine with dart-services.

### CODE REVIEW

**Comment by kevmoo** [comment]
@jcollins-g – you've double checked the tests? I'm freshly nervous about no CI.

**Comment by jcollins-g** [comment]
@kevmoo Yes, and I will check a third time before submitting.  :-)

**Comment by supermuka** [comment]
@jcollins-g, I tested and it works fine now in my use case.

**Comment by jcollins-g** [comment]
Retested with 2.0.0, 2.1.0, and 2.1.1-dev-1.0.  Landing and will publish shortly.

**Pull request merged**
